# Generated by Django 5.0.6 on 2024-07-05 08:44

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media')),
                ('description', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=50)),
                ('provider', models.CharField(max_length=50)),
                ('location', models.CharField(default='location', max_length=50)),
                ('price', models.FloatField()),
                ('duration', models.FloatField()),
                ('rating', models.FloatField(default='3.0')),
                ('review', models.CharField(default='review', max_length=100)),
                ('additional_info', models.CharField(default='additional info', max_length=300)),
            ],
            options={
                'db_table': 'service',
            },
            managers=[
                ('cserviceobj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SPService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media')),
                ('description', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=50)),
                ('provider', models.CharField(max_length=50)),
                ('location', models.CharField(default='location', max_length=50)),
                ('price', models.FloatField()),
                ('duration', models.FloatField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('additional_info', models.CharField(default='additional info', max_length=300)),
            ],
            options={
                'db_table': 'spservice',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=500)),
                ('usertype', models.CharField(max_length=50)),
                ('address_line1', models.CharField(max_length=50)),
                ('address_line2', models.CharField(default='area', max_length=50)),
                ('city', models.CharField(default='city', max_length=50)),
                ('state', models.CharField(default='state', max_length=50)),
                ('pincode', models.BigIntegerField()),
                ('contact', models.BigIntegerField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('service_time', models.TimeField()),
                ('totalamount', models.FloatField()),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypetapp.service')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypetapp.user')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
