# Generated by Django 5.0.6 on 2024-07-05 10:42

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypetapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='spservice',
            managers=[
                ('cspserviceobj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='spservice',
            name='rating',
            field=models.FloatField(default='3.0'),
        ),
        migrations.AddField(
            model_name='spservice',
            name='review',
            field=models.CharField(default='review', max_length=100),
        ),
    ]
