# Generated by Django 5.0.6 on 2024-07-05 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypetapp', '0003_alter_cart_service_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(max_length=100)),
                ('booking_date', models.DateField(auto_now=True)),
                ('booking_time', models.TimeField(auto_now=True)),
                ('booking_status', models.CharField(default='pending', max_length=100)),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypetapp.cart')),
            ],
            options={
                'db_table': 'booking',
            },
        ),
    ]
