# Generated by Django 5.0.6 on 2024-07-05 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypetapp', '0004_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cart_id',
        ),
    ]
