# Generated by Django 5.0.6 on 2024-07-06 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypetapp', '0006_booking_cart_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernumber', models.CharField(max_length=100)),
                ('orderdate', models.DateField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('phonenumber', models.BigIntegerField()),
                ('pincode', models.BigIntegerField()),
                ('orderstatus', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentmode', models.CharField(default='paypal', max_length=100)),
                ('paymentstatus', models.CharField(default='pending', max_length=100)),
                ('transactionid', models.CharField(max_length=200)),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypetapp.order')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypetapp.user')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Orderdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernumber', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('totalprice', models.IntegerField()),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('serviceid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypetapp.spservice')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypetapp.user')),
                ('paymentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypetapp.payment')),
            ],
            options={
                'db_table': 'orderdetail',
            },
        ),
    ]
