# Generated by Django 5.0.6 on 2024-07-06 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypetapp', '0007_order_payment_orderdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='quantity',
        ),
    ]
