# Generated by Django 5.0.6 on 2024-07-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypetapp', '0008_remove_orderdetail_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
